import '@/styles/globals.css'
import Head from 'next/head'
import type { AppProps } from 'next/app'
import { ThemeProvider } from '@mui/material'
import theme from '@/theme/theme'

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Prayers-Mui-CSS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <div style={{ border: "1px solid yellow", margin: "-9px" }}> */}

      < ThemeProvider theme={theme}>
        <Component {...pageProps} />
      </ThemeProvider>

    </>
  )
}
